# Generated by Django 3.1.4 on 2021-02-24 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_follower'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='user',
            new_name='followee',
        ),
    ]
